name: w_boson
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - anyio=4.12.0=pyhcf101f3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py312h4c3975b_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - brotli-python=1.2.0=py312hdb49522_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py312h460c074_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.12.12=py312hd8ed1ab_1
  - debugpy=1.8.17=py312h8285ef7_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py312h7900ff3_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.5.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lark=1.3.1=pyhd8ed1ab_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_14
  - libgcc-ng=15.2.0=h69a702a_14
  - libgomp=15.2.0=he0feb66_14
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.1=h0c1763c_0
  - libstdcxx=15.2.0=h934c35e_14
  - libstdcxx-ng=15.2.0=hdf11a46_14
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - markupsafe=3.0.3=py312h8a5da7c_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mistune=3.1.4=pyhcf101f3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - openssl=3.6.0=h26f9b46_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py312h5253ce2_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.12=hd63d673_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.12.12=hd8ed1ab_1
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py312h8a5da7c_0
  - pyzmq=27.1.0=py312hfb55c3c_0
  - readline=8.2=h8c095d6_2
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.29.0=py312h868fb18_0
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - terminado=0.18.1=pyh0d859eb_0
  - tinycss2=1.5.0=pyhcf101f3_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.2=py312h4c3975b_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstandard=0.25.0=py312h5253ce2_1
  - zstd=1.5.7=h3691f8a_4
  - pip:
      - atlasopenmagic==1.8.0
      - tqdm==4.67.1
prefix: /home/alangu/anaconda3/envs/w_boson
